### ISSUE TITLE
Great Work! and I have suggetion!

### ISSUE THREAD

**Issue by pessivesto** [Amadeus-AI/img2img-hires-fix#2]
I eagerly awaited the re-release of this expansion after the launch of WebUI. Thank you for your hard work. During several tests, I discovered one area for improvement. Would it be possible to have HIRES FIX run before ADetailer? Currently, Your I2I HIRES FIX runs after ADetailer, which destroys the facial image on xl,pony,flux. It would be great if this issue could be resolved.

**Comment by Amadeus-AI** [comment]
Hi! Thank you for the suggestion, but currently this extension is designed to be run after all process was done in i2i, because I want to keep the dependency and objective of this extension as simple as possible. Thank you for the understanding.

**Comment by Amadeus-AI** [comment]
Hi! Thank you for the suggestion, but currently this extension is designed to be run after all process was done in i2i, because I want to keep the dependency and objective of this extension as simple as possible. Thank you for the understanding.
