### ISSUE TITLE
Not showing after installed in Forge

### ISSUE THREAD

**Issue by krones9000** [Amadeus-AI/img2img-hires-fix#3]
Hi, I realize this is intended for A1111 so there may just be a comparability issues but I'm trying to use this in Forge and it's not showing in the UI after install and restart.

I get an error on launch of Forge and it's an ImportError, Python is unable to find or import the sd_schedulers module from a package called modules.

I will take a look myself but I'm not overly familiar with this so if you've got any input it would be appreciated.

**Comment by Amadeus-AI** [comment]
I just tested the extension on forge and it works fine.

**Comment by krones9000** [comment]
Hmm. Maybe it's me. I'll install again tomorrow and let you know what happens. Can I just check, install by pasting the github address into the "install from URL" should work as normal?

**Comment by krones9000** [comment]
Interesting. So I've got two versions of Forge, 1. a stable earlier version I've been using for a while and 2. the "newer" version which has some issues. It is showing in the new version. So I guess you can close this, thank you for your help.

Interestingly though I can't see any logical reason for it to encounter the error below but there you go.

```
line 8, in <module>
        from modules import scripts, shared, processing, sd_samplers, rng, images, devices, prompt_parser, sd_models, extra_networks, ui_components, sd_schedulers, script_callbacks, extra_networks
    ImportError: cannot import name 'sd_schedulers' from 'modules' (unknown location)
```
